spring:
  data:
    mongodb:
      username: shubham
      password: shubham
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
