spring:
  data:
    mongodb:
      username: shubham
      password: shubham
      host: ms_mongo_db
      port: 27017
      database: customer
      authentication-database: admin
eureka:
  instance:
    hostname: customer-service
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
server:
  port: 8090
