spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: shubhamshinde0803@gmail.com
    password:
